
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-06T21:13:02-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "87349f0f87bf32364a2a2316f6465566c6ab46f4",
 "version": "4.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
