
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-25T10:14:09-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "957b01002dcd33f0f45232caf03b463d43b46a72",
 "version": "4.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
